name = world_limit
description = An API for server owners to make a virtual boundary, this dont creates any visual elements jist warns the player and teleports them back if they cross that boundary, default limit is 2000 in x, z axis not counting y axis
author = Gemini 2.5 Flash
prompter = jolethen
